name: Build

on:
  push

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
    - name: build pocket2rm
      run: |
        cd cmd/pocket2rm
        GOOS=linux GOARCH=arm GOARM=7 go build -o pocket2rm.arm
    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: pocket2rm.arm
        path: cmd/pocket2rm/pocket2rm.arm
